---
 - hosts: client
   vars_files:
     - ../vault.yml
   become: true
   vars:
     ansible_become: yes
     ansible_become_pass: "{{ password }}" 
     ansible_python_interpreter: "/usr/bin/python3"
   tasks:
   - name: Install web browser
     ansible.builtin.apt: name=chromium state=present update_cache=yes